name: zephyr
dependencies:
  - python>=3.7.0
  - numpy>=1.19.1
  - pandas>=1.1.0
  - xarray>=0.12.3
  - matplotlib>=3.1.1
  - scipy>=1.3.1
  - pip>=20.2.2
  - geopandas>=0.6.1
  - requests>=2.24.0
  - tqdm
  - ipykernel
  - openpyxl
  - pip:
    # - pvlib>=0.7.1
    - pvlib==0.7.*
    - pulp>=1.6.*
    - jenkspy>=0.1.5
    - geopy>=1.19.0
    - h5pyd>=0.6.0
